---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dbhpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: StatefulSet
    name: dbstatefulset
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
