---
apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
  namespace: dev
type: Opaque
data: 
  MYSQL_ROOT_PASSWORD: YWRtaW4xMjM=
  MYSQL_PASSWORD: YWRtaW4xMjM=
  MYSQL_USER: YWRtaW4=
  MYSQL_DATABASE: bXlzcWw=
